# Example configuration for Neewer GL25C Light integration

# Basic configuration with just the required host parameter
light:
  - platform: neewer_gl25c
    host: 192.168.1.100

# Full configuration with all options
light:
  - platform: neewer_gl25c
    name: "Studio Light"
    host: 192.168.1.100
    port: 5052

# Multiple lights configuration
light:
  - platform: neewer_gl25c
    name: "Key Light"
    host: 192.168.1.101
    
  - platform: neewer_gl25c
    name: "Fill Light"
    host: 192.168.1.102
    
  - platform: neewer_gl25c
    name: "Background Light"
    host: 192.168.1.103

# Example automation using the light
automation:
  - alias: "Turn on studio lights at sunset"
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: light.turn_on
        target:
          entity_id: light.studio_light
        data:
          brightness_pct: 80
          kelvin: 5500

  - alias: "Dim lights for movie time"
    trigger:
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'playing'
    action:
      - service: light.turn_on
        target:
          entity_id: light.studio_light
        data:
          brightness_pct: 20
          kelvin: 3000

# Example script for video recording setup
script:
  video_recording_setup:
    alias: "Video Recording Light Setup"
    sequence:
      - service: light.turn_on
        target:
          entity_id: light.key_light
        data:
          brightness_pct: 100
          kelvin: 5600
      - service: light.turn_on
        target:
          entity_id: light.fill_light
        data:
          brightness_pct: 60
          kelvin: 5600
      - service: light.turn_on
        target:
          entity_id: light.background_light
        data:
          brightness_pct: 40
          kelvin: 3200